FROM apache:alpine

# Import apache config for http
ADD ./apache.conf /etc/apache2/sites-available/app.conf

# Enable site
# Enable new site HTTP
RUN /usr/sbin/a2ensite app.conf

# Disable default Apache site
RUN /usr/sbin/a2dissite 000-default.conf

# Reload apache
CMD ["/etc/init.d/apache2", "restart"]
