FROM postgresql:alpine

USER postgres

# Create table and Add all privileges for postgres user
RUN /etc/init.d/postgresql start && psql -c "\set AUTOCOMMIT on\nALTER USER postgres WITH ENCRYPTED PASSWORD 'postgres';CREATE DATABASE laravelapp OWNER=postgres;"
# 


# Reload apache
CMD ["/etc/init.d/postgresql", "restart"]
